<?
    require_once('./dao/DAO.php');
    require_once('./dao/FactoryBD.php');
    //require_once('./dao/RecursoDAO.php');
    //require_once('./model/Recurso.php');
    require_once('./config/conexionBD.php');
    require_once('./controller/FatherController.php');
    require_once('./controller/numeroController.php');
?>